- include_tasks: variables.yml

- name: Tap homebrew fonts.
  community.general.homebrew_cask:
    name: homebrew/cask-fonts
  when: ansible_distribution == "MacOSX"

- name: Install zsh.
  package:
    name: "{{ pkg_zsh }}"
    state: present

- name: Install fira-code-fonts.
  package:
    name: "{{ pkg_fira_code_fonts }}"
    state: present

- name: Install kitty terminal.
  package:
    name: "{{ pkg_kitty }}"
    state: present

- name: Uninstall snapd.
  package:
    name: "{{ pkg_snapd }}"
    state: absent

- name: Install vlc.
  package:
    name: "{{ pkg_vlc }}"
    state: present

- name: Install newsboat.
  package:
    name: "{{ pkg_newsboat }}"
    state: present

- name: Install mpv.
  package:
    name: "{{ pkg_mpv }}"
    state: present
